import type { Job, Company, JobCategory, ContractType } from './types';

export const companies: Company[] = [
  { id: '1', name: 'TechCorp', logoId: 'logo-techcorp' },
  { id: '2', name: 'Innovate Inc.', logoId: 'logo-innovateinc' },
  { id: '3', name: 'DataDigits', logoId: 'logo-datadigits' },
  { id: '4', name: 'CloudWave', logoId: 'logo-cloudwave' },
  { id: '5', name: 'DesignStudio', logoId: 'logo-designstudio' },
  { id: '6', name: 'MarketMinds', logoId: 'logo-marketminds' },
];

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: companies[0],
    location: 'San Francisco, CA',
    category: 'Engineering',
    contractType: 'Full-time',
    salary: '$120,000 - $160,000',
    description: 'We are looking for a seasoned frontend developer to build beautiful and performant user interfaces with React and Next.js.',
    requirements: ['5+ years of experience with React', 'Expertise in TypeScript, HTML, and CSS', 'Experience with Next.js is a plus', 'Strong understanding of web performance'],
    responsibilities: ['Develop new user-facing features', 'Build reusable code and libraries for future use', 'Ensure the technical feasibility of UI/UX designs', 'Optimize application for maximum speed and scalability'],
    postedAt: '2024-05-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'UX/UI Designer',
    company: companies[4],
    location: 'New York, NY',
    category: 'Design',
    contractType: 'Full-time',
    salary: '$90,000 - $110,000',
    description: 'DesignStudio is seeking a creative UX/UI designer to create intuitive and engaging experiences for our clients.',
    requirements: ['3+ years of UX/UI design experience', 'Proficient in Figma, Sketch, or Adobe XD', 'Strong portfolio of design projects', 'Excellent visual design skills'],
    responsibilities: ['Conduct user research and evaluate user feedback', 'Create wireframes, storyboards, user flows, process flows and site maps', 'Design and deliver mockups and prototypes', 'Collaborate with product management and engineering'],
    postedAt: '2024-05-19T14:30:00Z',
  },
  {
    id: '3',
    title: 'Digital Marketing Manager',
    company: companies[5],
    location: 'Remote',
    category: 'Marketing',
    contractType: 'Full-time',
    salary: '$85,000 - $105,000',
    description: 'MarketMinds is looking for a results-driven Digital Marketing Manager to lead our online marketing efforts.',
    requirements: ['Proven experience in digital marketing', 'Expertise in SEO, SEM, and social media marketing', 'Experience with Google Analytics and CRM software', 'Strong analytical skills'],
    responsibilities: ['Plan and execute all digital marketing campaigns', 'Measure and report on the performance of all digital marketing campaigns', 'Identify trends and insights, and optimize spend and performance based on the insights', 'Brainstorm new and creative growth strategies'],
    postedAt: '2024-05-21T11:00:00Z',
  },
  {
    id: '4',
    title: 'Backend Engineer (Node.js)',
    company: companies[3],
    location: 'Austin, TX',
    category: 'Engineering',
    contractType: 'Full-time',
    salary: '$110,000 - $140,000',
    description: 'Join DataDigits to build and maintain the server-side logic of our applications. You will be working with Node.js, Express, and PostgreSQL.',
    requirements: ['4+ years of backend development experience', 'Strong proficiency with Node.js and TypeScript', 'Experience with relational databases like PostgreSQL', 'Familiarity with containerization (Docker, Kubernetes)'],
    responsibilities: ['Design and implement low-latency, high-availability, and performant applications', 'Write reusable, testable, and efficient code', 'Integration of data storage solutions', 'Implement security and data protection'],
    postedAt: '2024-05-18T09:00:00Z',
  },
  {
    id: '5',
    title: 'Product Manager',
    company: companies[1],
    location: 'Remote',
    category: 'Product',
    contractType: 'Full-time',
    salary: '$130,000 - $170,000',
    description: 'Innovate Inc. needs a visionary Product Manager to own the product lifecycle from strategy to execution.',
    requirements: ['5+ years of product management experience', 'Proven track record of managing all aspects of a successful product throughout its lifecycle', 'Solid technical background with understanding and/or hands-on experience in software development', 'Excellent problem-solving skills'],
    responsibilities: ['Define the product vision, strategy, and roadmap', 'Gather and prioritize product and customer requirements', 'Work closely with engineering, sales, marketing, and support to ensure revenue and customer satisfaction goals are met', 'Act as a product evangelist to build awareness and understanding'],
    postedAt: '2024-05-22T08:00:00Z',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: companies[3],
    location: 'Chicago, IL',
    category: 'Engineering',
    contractType: 'Full-time',
    salary: '$125,000 - $155,000',
    description: 'We are seeking a DevOps Engineer to help us build and maintain our cloud infrastructure and automate our development pipelines.',
    requirements: ['Experience with AWS or GCP', 'Strong background in Linux/Unix Administration', 'Experience with automation/configuration management using either Puppet, Chef or an equivalent', 'Ability to code and script in Python, Go, or Bash'],
    responsibilities: ['Manage and improve our CI/CD process', 'Build and maintain our monitoring and alerting systems', 'Work with development teams to ensure services are scalable and reliable', 'Automate everything'],
    postedAt: '2024-05-17T16:00:00Z',
  },
];
